server:
  port: 8080
spring:
  application:
    name: "AUTENTICACION"
  devtools:
    add-properties: false
  profiles:
    include: null
adapters:
  r2dbc:
    type: "mysql"
    host: "127.0.0.1"
    port: 3307
    database: "autenticacion"
    username: "appuser"
    password: "app_pass_123"
logging:
  level:
    io.r2dbc.mysql.QUERY: DEBUG # Para ver las queries
    io.r2dbc.mysql.PARAM: DEBUG
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081 "

routes:
  paths:
    createUsuario: "/api/v1/usuario"
    searchUsuario: "/api/v1/usuario/{email}"
