server:
  port: 8080
spring:
  application:
    name: "AUTENTICACION"
  devtools:
    add-properties: false
  profiles:
    include: null
adapters:
  r2dbc:
    type: "mysql"
    host: "127.0.0.1"
    port: 3307
    database: "autenticacion"
    username: "appuser"
    password: "app_pass_123"
logging:
  level:
    io.r2dbc.mysql.QUERY: DEBUG # Para ver las queries
    io.r2dbc.mysql.PARAM: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web.server: DEBUG
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"

routes:
  paths:
    login: "/api/v1/login"
    createUsuario: "/api/v1/usuario"
    updateUsuarioToClient: "/api/v1/usuario/update/{email}"

app:
  security:
    bcrypt-strength: ${BCRYPT_STRENGTH:12}

# Configuración JWT (misma que en microservicios)
jwt:
  secret: bWlDbGF2ZVNlY3JldGFNdXlMYXJnYVBhcmFKV1RDb25BbE1lbm9zMzJDYXJhY3RlcmVzUGFyYVNlZ3VyaWRhZA==
  expiration: 86400000  # 24 horas