##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: AUTENTICACION
  devtools:
    add-properties: false
  profiles:
    include: null
adapters:
  r2dbc:
    host: 127.0.0.1
    port: 3307
    database: autenticacion
    username: appuser
    password: app_pass_123